// src/reports/generateIndividualPdf.js
// Builds the per-employee monthly report as a real PDF (no print dialog), so the
// "all staff" download can zip one file per person.

import { jsPDF } from 'jspdf';
import { autoTable } from 'jspdf-autotable';
import JSZip from 'jszip';
import { costBreakdown, formatHoursMinutes } from '../lib/helpers';

// PDF standard fonts lack the narrow no-break space nb-NO uses as a thousands separator
const nok = (n) => `${Math.round(n).toLocaleString('nb-NO').replace(/\s/g, ' ')} NOK`;
const signed = (n) => `${n > 0 ? '+' : ''}${Number(n).toFixed(2)}h`;

// ASCII-only so every unzip tool keeps the name intact (Gåsvatn -> Gasvatn).
const safeFileName = (s) =>
  s.trim()
    .replace(/æ/g, 'ae').replace(/Æ/g, 'Ae').replace(/ø/g, 'o').replace(/Ø/g, 'O')
    .normalize('NFD').replace(/[\u0300-\u036f]/g, '')
    .replace(/\s+/g, '_').replace(/[^A-Za-z0-9_-]/g, '');

export function individualPdfFileName(employee, monthName, year) {
  return `${safeFileName(employee.name)}_${monthName}_${year}.pdf`;
}

// `stats.totalHours` must be decimal hours (e.g. 112.9), not the "X hrs Y min" string.
export function buildIndividualPdf({ employee, monthName, year, stats, timeEntries }) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();
  const m = 15;
  const { baseSalary, aga, otp, feriepenger, realCost } = costBreakdown(stats.totalHours, employee.wage);

  // Header
  doc.setFont('helvetica', 'bold').setFontSize(16).setTextColor(30, 41, 59);
  doc.text(employee.name.trim(), m, 20);
  doc.setFont('helvetica', 'normal').setFontSize(11).setTextColor(100, 116, 139);
  doc.text(`${monthName} ${year}`, m, 26);
  doc.setFontSize(10);
  doc.text(employee.role || 'N/A', pageW - m, 20, { align: 'right' });
  doc.setFontSize(9);
  doc.text(`${employee.wage ?? 'N/A'} NOK/h • ${employee.percentage ?? '--'}%`, pageW - m, 26, { align: 'right' });
  doc.setDrawColor(37, 99, 235).setLineWidth(0.8).line(m, 30, pageW - m, 30);

  // Summary
  autoTable(doc, {
    startY: 35,
    margin: { left: m, right: m },
    theme: 'grid',
    head: [['Total Hours', 'Work Days', 'Difference', 'Base Salary', 'Real Cost (w/ taxes)']],
    body: [[
      formatHoursMinutes(stats.totalHours),
      String(stats.workDays ?? 0),
      signed(stats.overtimeHours ?? 0),
      nok(baseSalary),
      nok(realCost),
    ]],
    headStyles: { fillColor: [241, 245, 249], textColor: [100, 116, 139], fontSize: 8 },
    bodyStyles: { fontSize: 11, fontStyle: 'bold', textColor: [30, 41, 59] },
  });

  let y = doc.lastAutoTable.finalY + 6;
  doc.setFont('helvetica', 'normal').setFontSize(9).setTextColor(71, 85, 105);
  doc.text(
    `AGA (14.1%): ${nok(aga)}    OTP (2%): ${nok(otp)}    Feriepenger (10.2%): ${nok(feriepenger)}`,
    m, y,
  );

  // Time entries
  autoTable(doc, {
    startY: y + 5,
    margin: { left: m, right: m },
    head: [['Date', 'Shift', 'Clock In', 'Clock Out', 'Break', 'Actual', 'Diff']],
    body: timeEntries.map(e => [
      e.date, e.shiftName || '', e.clockIn, e.clockOut, `${e.breakHours}h`, `${e.actualHours}h`,
      `${parseFloat(e.difference) > 0 ? '+' : ''}${e.difference}h`,
    ]),
    headStyles: { fillColor: [30, 41, 59], fontSize: 8 },
    bodyStyles: { fontSize: 8 },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    didParseCell: (data) => {
      if (data.section === 'body' && data.column.index === 6) {
        const d = parseFloat(data.cell.raw);
        if (d > 0) data.cell.styles.textColor = [5, 150, 105];
        if (d < 0) data.cell.styles.textColor = [220, 38, 38];
      }
    },
  });

  const generated = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  const pageCount = doc.getNumberOfPages();
  for (let p = 1; p <= pageCount; p++) {
    doc.setPage(p);
    doc.setFontSize(8).setTextColor(100, 116, 139);
    doc.text(`Generated by Staff Management System • ${generated}`, pageW / 2, 290, { align: 'center' });
  }

  return doc;
}

// One PDF per employee in a single zip download.
export async function downloadAllIndividualPdfs({ employeesWithData, monthName, year }) {
  const zip = new JSZip();
  for (const emp of employeesWithData) {
    const doc = buildIndividualPdf({
      employee: emp,
      monthName,
      year,
      stats: emp.stats,
      timeEntries: emp.timeEntries,
    });
    zip.file(individualPdfFileName(emp, monthName, year), doc.output('arraybuffer'));
  }
  const blob = await zip.generateAsync({ type: 'blob' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `Staff_Reports_${monthName}_${year}.zip`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}
